<CustButton@Button>:
    font_size: 23
    color: 0, 0, 0, 1
    size: 150, 50
    background_normal: ''
    background_down: '1.png'
    background_color: .88, .88, .88, 1

<CustomWidget>:
    CustButton:
        text: "Button 1"
        pos: root.x, 200

    CustButton:
        text: "Button 2"
        pos: 200, root.y

    CustButton:
        text: "Random"
        pos: 200, 400